const jobs = [
    // Trabajos de JavaScript
    {
        title: "Desarrollador JavaScript Trainee",
        description: "Desarrollador de aplicaciones web sin experiencia, pero con conocimientos de programación.",
        englishRequired: true,
        language: "JavaScript",
        seniority: "Trainee",
        annualSalary: "U$D 20,000",
        datePosted: new Date(2023, 9, 25), 
    },
    {
        title: "Desarrollador JavaScript Senior",
        description: "Desarrollador de aplicaciones web con experiencia en JavaScript.",
        englishRequired: true,
        language: "JavaScript",
        seniority: "Senior",
        annualSalary: "U$D 70,000",
        datePosted: new Date(2023, 2, 15),
    },
    {
        title: "Desarrollador Full Stack JavaScript Senior",
        description: "Desarrollador full stack con experiencia en JavaScript y frameworks.",
        englishRequired: false,
        language: "JavaScript",
        seniority: "Senior",
        annualSalary: "U$D 75,000",
        datePosted: new Date(2023, 1, 20), 
    },
    {
        title: "Desarrollador Frontend JavaScript Semi Senior",
        description: "Especialista en desarrollo frontend con experiencia en JavaScript.",
        englishRequired: true,
        language: "JavaScript",
        seniority: "SemiSenior",
        annualSalary: "U$D 55,000",
        datePosted: new Date(2023, 2, 10),
    },
    {
        title: "Ingeniero de Software JavaScript Trainee",
        description: "Programador JavaScript en formación para proyectos de desarrollo web.",
        englishRequired: false,
        language: "JavaScript",
        seniority: "Trainee",
        annualSalary: "U$D 25,000",
        datePosted: new Date(2023, 8, 5), 
    },
    {
        title: "Diseñador Web JavaScript Senior",
        description: "Diseñador web con experiencia en JavaScript y tecnologías frontend.",
        englishRequired: true,
        language: "JavaScript",
        seniority: "Senior",
        annualSalary: "U$D 65,000",
        datePosted: new Date(2023, 10, 20), 
    },
    {
        title: "Desarrollador Full Stack JavaScript Junior",
        description: "Programador full stack con conocimientos de JavaScript y frameworks.",
        englishRequired: false,
        language: "JavaScript",
        seniority: "Junior",
        annualSalary: "U$D 40,000",
        datePosted: new Date(2023, 3, 5), 
    },
    {
        title: "Desarrollador JavaScript Senior",
        description: "Desarrollador web con experiencia en JavaScript y aplicaciones móviles.",
        englishRequired: true,
        language: "JavaScript",
        seniority: "Senior",
        annualSalary: "U$D 70,000",
        datePosted: new Date(2023, 2, 15), 
    },
    {
        title: "Desarrollador Frontend JavaScript Semi Senior",
        description: "Especialista en desarrollo frontend con experiencia en JavaScript.",
        englishRequired: true,
        language: "JavaScript",
        seniority: "SemiSenior",
        annualSalary: "U$D 55,000",
        datePosted: new Date(2023, 1, 10), 
    },
    {
        title: "Ingeniero de Software JavaScript Trainee",
        description: "Programador JavaScript en formación para proyectos de desarrollo web.",
        englishRequired: false,
        language: "JavaScript",
        seniority: "Trainee",
        annualSalary: "U$D 25,000",
        datePosted: new Date(2023, 10, 5), 
    },
    {
        title: "Diseñador Web JavaScript Senior",
        description: "Diseñador web con experiencia en JavaScript y tecnologías frontend.",
        englishRequired: true,
        language: "JavaScript",
        seniority: "Senior",
        annualSalary: "U$D 65,000",
        datePosted: new Date(2023, 9, 10), 
    },
    {
        title: "Desarrollador Full Stack JavaScript Junior",
        description: "Programador full stack con conocimientos de JavaScript y frameworks.",
        englishRequired: false,
        language: "JavaScript",
        seniority: "Junior",
        annualSalary: "U$D 40,000",
        datePosted: new Date(2023, 9, 5), 
    },

    // Trabajos de Python
    {
        title: "Analista de Datos Junior",
        description: "Analista de datos para procesar y analizar información empresarial.",
        englishRequired: false,
        language: "Python",
        seniority: "Junior",
        annualSalary: "U$D 45,000",
        datePosted: new Date(2023, 1, 10), 
    },
    {
        title: "Desarrollador Python Senior",
        description: "Desarrollador con experiencia en Python para proyectos de inteligencia artificial.",
        englishRequired: true,
        language: "Python",
        seniority: "Senior",
        annualSalary: "U$D 75,000",
        datePosted: new Date(2023, 0, 5), 
    },
    {
        title: "Desarrollador Python Junior",
        description: "Programador Python con conocimientos en desarrollo web y aplicaciones empresariales.",
        englishRequired: false,
        language: "Python",
        seniority: "Junior",
        annualSalary: "U$D 50,000",
        datePosted: new Date(2023, 9, 20), 
    },
    {
        title: "Ingeniero de Datos Python Semi Senior",
        description: "Especialista en procesamiento de datos con Python para análisis de datos empresariales.",
        englishRequired: true,
        language: "Python",
        seniority: "SemiSenior",
        annualSalary: "U$D 60,000",
        datePosted: new Date(2023, 1, 15), 
    },
    {
        title: "Desarrollador Python Full Stack Senior",
        description: "Programador full stack con experiencia en Python y frameworks web.",
        englishRequired: false,
        language: "Python",
        seniority: "Senior",
        annualSalary: "U$D 70,000",
        datePosted: new Date(2023, 9, 5), 
    },
    {
        title: "Analista de Datos Python Trainee",
        description: "Analista de datos en formación con conocimientos básicos de Python.",
        englishRequired: true,
        language: "Python",
        seniority: "Trainee",
        annualSalary: "U$D 30,000",
        datePosted: new Date(2023, 9, 10),
    },
    {
        title: "Desarrollador Python Semi Senior",
        description: "Programador Python con experiencia en desarrollo de aplicaciones web y móviles.",
        englishRequired: false,
        language: "Python",
        seniority: "SemiSenior",
        annualSalary: "U$D 55,000",
        datePosted: new Date(2023, 3, 1), 
    },
    {
        title: "Ingeniero de Datos Python Trainee",
        description: "Especialista en procesamiento de datos con Python en formación.",
        englishRequired: true,
        language: "Python",
        seniority: "Trainee",
        annualSalary: "U$D 35,000",
        datePosted: new Date(2023, 0, 15),
    },

    // Trabajos de Java
    {
        title: "Ingeniero de Software Trainee",
        description: "Programador en formación para proyectos de software.",
        englishRequired: true,
        language: "Java",
        seniority: "Trainee",
        annualSalary: "U$D 30,000",
        datePosted: new Date(2023, 8, 5), 
    },
    {
        title: "Ingeniero Java Senior",
        description: "Desarrollador de aplicaciones empresariales en Java.",
        englishRequired: true,
        language: "Java",
        seniority: "Senior",
        annualSalary: "U$D 80,000",
        datePosted: new Date(2023, 1, 10), 
    },
    {
        title: "Desarrollador Java Semi Senior",
        description: "Programador Java con experiencia en desarrollo web y aplicaciones empresariales.",
        englishRequired: false,
        language: "Java",
        seniority: "SemiSenior",
        annualSalary: "U$D 60,000",
        datePosted: new Date(2023, 0, 15), 
    },
    {
        title: "Ingeniero Java Junior",
        description: "Desarrollador Java con conocimientos en desarrollo de aplicaciones móviles.",
        englishRequired: true,
        language: "Java",
        seniority: "Junior",
        annualSalary: "U$D 45,000",
        datePosted: new Date(2023, 9, 20), 
    },
    {
        title: "Desarrollador Java Trainee",
        description: "Programador Java en formación para proyectos de desarrollo de software.",
        englishRequired: false,
        language: "Java",
        seniority: "Trainee",
        annualSalary: "U$D 35,000",
        datePosted: new Date(2023, 2, 5),
    },
    {
        title: "Ingeniero de Software Java Senior",
        description: "Desarrollador de aplicaciones empresariales en Java y sistemas embebidos.",
        englishRequired: true,
        language: "Java",
        seniority: "Senior",
        annualSalary: "U$D 85,000",
        datePosted: new Date(2023, 2, 10), 
    },
    {
        title: "Analista Java Junior",
        description: "Analista de sistemas Java para proyectos de análisis de datos.",
        englishRequired: false,
        language: "Java",
        seniority: "Junior",
        annualSalary: "U$D 50,000",
        datePosted: new Date(2023, 3, 25), 
    },
    {
        title: "Ingeniero Java Semi Senior",
        description: "Desarrollador Java con experiencia en desarrollo web y aplicaciones empresariales.",
        englishRequired: true,
        language: "Java",
        seniority: "SemiSenior",
        annualSalary: "U$D 70,000",
        datePosted: new Date(2023, 0, 15),
    },
    {
        title: "Ingeniero de Software Java Trainee",
        description: "Programador Java en formación para proyectos de desarrollo de software.",
        englishRequired: false,
        language: "Java",
        seniority: "Trainee",
        annualSalary: "U$D 35,000",
        datePosted: new Date(2023, 9, 5), 
    },
    {
        title: "Desarrollador Java Junior",
        description: "Programador Java con conocimientos en desarrollo web y aplicaciones móviles.",
        englishRequired: true,
        language: "Java",
        seniority: "Junior",
        annualSalary: "U$D 45,000",
        datePosted: new Date(2023, 2, 10), 
    },
    {
        title: "Ingeniero de Software Java Semi Senior",
        description: "Desarrollador Java con experiencia en desarrollo de aplicaciones empresariales.",
        englishRequired: false,
        language: "Java",
        seniority: "SemiSenior",
        annualSalary: "U$D 65,000",
        datePosted: new Date(2023, 5, 15),
    },
    {
        title: "Analista Java Senior",
        description: "Analista de sistemas Java con experiencia en proyectos de análisis de datos.",
        englishRequired: true,
        language: "Java",
        seniority: "Senior",
        annualSalary: "U$D 80,000",
        datePosted: new Date(2023, 3, 5), 
    },

    // Trabajos de SQL
    {
        title: "Analista de Datos SQL Semi Senior",
        description: "Analista de datos para consultas SQL y análisis de bases de datos.",
        englishRequired: false,
        language: "SQL",
        seniority: "SemiSenior",
        annualSalary: "U$D 55,000",
        datePosted: new Date(2023, 2, 1), 
    },
    {
        title: "Analista de Datos SQL Junior",
        description: "Analista de datos para consultas SQL y análisis estadístico.",
        englishRequired: true,
        language: "SQL",
        seniority: "Junior",
        annualSalary: "U$D 50,000",
        datePosted: new Date(2023, 10, 1), 
    },
    {
        title: "Ingeniero de Datos SQL Senior",
        description: "Especialista en bases de datos SQL para análisis de datos empresariales.",
        englishRequired: true,
        language: "SQL",
        seniority: "Senior",
        annualSalary: "U$D 70,000",
        datePosted: new Date(2023, 0, 10), 
    },
    {
        title: "Desarrollador SQL Trainee",
        description: "Programador SQL en formación para proyectos de bases de datos y consultas.",
        englishRequired: false,
        language: "SQL",
        seniority: "Trainee",
        annualSalary: "U$D 35,000",
        datePosted: new Date(2023, 9, 10), 
    },
    {
        title: "Analista SQL Semi Senior",
        description: "Analista de bases de datos SQL con experiencia en análisis empresarial.",
        englishRequired: true,
        language: "SQL",
        seniority: "SemiSenior",
        annualSalary: "U$D 60,000",
        datePosted: new Date(2023, 3, 5), 
    },
    {
        title: "Ingeniero de Datos SQL Trainee",
        description: "Especialista en bases de datos SQL en formación para análisis de datos empresariales.",
        englishRequired: false,
        language: "SQL",
        seniority: "Trainee",
        annualSalary: "U$D 35,000",
        datePosted: new Date(2023, 8, 20), 
    },
    {
        title: "Analista SQL Junior",
        description: "Analista de bases de datos SQL para consultas y análisis estadístico.",
        englishRequired: false,
        language: "SQL",
        seniority: "Junior",
        annualSalary: "U$D 45,000",
        datePosted: new Date(2023, 1, 15), 
    },
    {
        title: "Desarrollador SQL Semi Senior",
        description: "Programador SQL con experiencia en desarrollo de bases de datos y consultas.",
        englishRequired: true,
        language: "SQL",
        seniority: "SemiSenior",
        annualSalary: "U$D 65,000",
        datePosted: new Date(2023, 10, 25),
    },
    {
        title: "Analista de Datos SQL Trainee",
        description: "Analista de datos SQL en formación para proyectos de análisis de información.",
        englishRequired: true,
        language: "SQL",
        seniority: "Trainee",
        annualSalary: "U$D 40,000",
        datePosted: new Date(2023, 2, 10), 
    },
    {
        title: "Desarrollador SQL Junior",
        description: "Programador SQL con conocimientos en desarrollo de bases de datos empresariales.",
        englishRequired: true,
        language: "SQL",
        seniority: "Junior",
        annualSalary: "U$D 50,000",
        datePosted: new Date(2023, 10, 5), 
    }
];

export default jobs;
